apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: arbritrary-example
spec:
  backendType: ibmcloudSecretsManager
  data: 
    # The guid id of the secret
    # Created with ibmcloud secrets-manager secret-create --secret-type arbitrary \
    # --resources '[{"name": "example-arbitrary-test-secret","description": "Extended description for my secret.", "payload":"avalue"}]'
    - key: <guid> 
      name: example-arbitrary-test-secret
      property: payload
      secretType: arbitrary