apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: ibmcloud-secrets-manager-example
spec:
  backendType: ibmcloudSecretsManager
  data:
    # The guid id of the secret
    - key: <guid>
      name: username
      property: username
      secretType: username_password
    - key: <guid>
      name: password
      property: password
      secretType: username_password