apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: username-password-example
spec:
  backendType: ibmcloudSecretsManager
  data:
    # The guid id of the secret created with:
    # ibmcloud secrets-manager secret-create --secret-type username_password 
    # --resources '[{"name": "example-username-password-test-secret","description": "Extended description for my secret.",
    # "username": "user123","password": "cloudy-rainy-coffee-book"}]'
    - key: <guid>
      name: username
      property: username
      secretType: username_password
    - key: <guid>
      name: password
      property: password
      secretType: username_password